#!/bin/bash
#   Compile script for ARM Android.
# TOOLCHAIN needs to be set to the location of the toolchain,
#    for example: /opt/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86 
# SYSROOT must be set to the location of the ndk sys root,
#    for example: /opt/ndk/platforms/android-14/arch-arm

TOOLCHAIN=/home/susingha/checkout/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/
SYSROOT=/home/susingha/checkout/android-ndk-r9d/platforms/android-14/arch-arm/
GCC=${TOOLCHAIN}/bin/arm-linux-androideabi-gcc
CFLAGS="-g3 --sysroot=${SYSROOT}"

#rm -f *.so main

#${GCC} ${CFLAGS} -fPIC -shared -o libmydyn1.so libmydyn1.c
${GCC} ${CFLAGS} -fPIC -shared -o libmydyn2.so libmydyn2.c

#${GCC} ${CFLAGS} -L$PWD -fPIC -shared -o libintermediate.so libintermediate.c -lmydyn1
#${GCC} ${CFLAGS} -L$PWD -o main main.c -lintermediate -ldl



